### ISSUE TITLE
SPDLOG_TRACE evaluate their arguments even when logging is off

### ISSUE THREAD

**Issue by jwnimmer-tri** [gabime/spdlog#1262]
I think that commit e1be7f3d6f65ec16551ade0a7939ad24834f5070 introduced a regression in `SPDLOG_LOGGER_TRACE` (and similar) -- the feature from #638 no longer works:

```c++
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG

TEST_CASE("macros leave args unevaluated", "[macros]") {
  // Shouldn't evaluate any macro arguments when logging is off.
  auto logger = spdlog::create<spdlog::sinks::basic_file_sink_mt>("logger", "some_file");
  logger->set_level(spdlog::level::off);
  int arg = 0;
  SPDLOG_LOGGER_DEBUG(logger, "arg={}", ++arg);
  REQUIRE(arg == 0);
}
```

In v1.3.1 this test passes, in v1.4.2 it fails.

See https://github.com/gabime/spdlog/commit/e1be7f3d6f65ec16551ade0a7939ad24834f5070#diff-ec88af83a0f1976c3c605e8b1027c454.

**Comment by gabime** [comment]
Thanks for reporting. This changed after the support for the new backtrace feature(which, if enabled, saves all messages to ring buffer for later). 

I will need  to think how to solve this and still have sensible backtrace support.

**Comment by jwnimmer-tri** [comment]
I've been playing around with some potential fixes locally.  Of course choosing the semantics is the first step.

My own vote would be that if the user has enabled tracing, and the compile-time LEVEL for the macro is met, then the message should be saved into the trace buffer (evaluating the macro arguments) even if the runtime log level threshold is unmet.  That seems to be like the principle of least surprise.

The naive implementation of this is to add the level + tracing check inside the CALL macro, while keeping `logger::log` unchanged (so redundantly checking), but I'm a little worried about the object code and possible performance hit.

**Comment by gabime** [comment]
> The naive implementation of this is to add the level + tracing check inside the CALL macro, while keeping logger::log unchanged (so redundantly checking), but I'm a little worried about the object code and possible performance hit.

Yes, that my opinion as well. Need to bench and see. If it will hurt the performance (which i doubt), a dedicated, new ```force_log``` function that doesn't check for the level can used from the macro.

**Comment by jwnimmer-tri** [comment]
FYI One other thing I noticed while playing with this locally -- it's possible that the `logger` macro argument either has side-effects or is expensive to compute.  As an enhancement, it would be nice if the macro only evaluated that argument once.

**Comment by gabime** [comment]
Any idea how to achive this ?
I tried this binding to some variable: 
```c++
#define SPDLOG_LOGGER_CALL(logger, level, ...) do {\
    auto &eval_logger = logger;\
    if(eval_logger->should_log(level) || eval_logger->should_backtrace()) \
        eval_logger->log(spdlog::source_loc{__FILE__, __LINE__, SPDLOG_FUNCTION}, level, __VA_ARGS__);\
    } while(0)
``` 
but got compiler errors about r values.
```console

In file included from /home/gabi/spdlog/tests/includes.h:17,
                 from /home/gabi/spdlog/tests/test_macros.cpp:5:
/home/gabi/spdlog/tests/test_macros.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____0()’:
/home/gabi/spdlog/include/spdlog/spdlog.h:304:73: error: cannot bind non-const lvalue reference of type ‘spdlog::logger*&’ to an rvalue of type ‘spdlog::logger*’
 #define SPDLOG_DEBUG(...) SPDLOG_LOGGER_DEBUG(spdlog::default_logger_raw(), __VA_ARGS__)

```

**Comment by gabime** [comment]
Fixed in 9369fe8c27260ca7929559a0f4e11980a8b3ade6

**Comment by jwnimmer-tri** [comment]
My attempt went like
```c++
#define SPDLOG_LOGGER_CALL(logger, level, ...) do { \
    spdlog::logger* spdlog_logger_temporary_detail = logger; \
    if(spdlog_logger_temporary_detail->foo()) \
        spdlog_logger_temporary_detail->bar() \
} while (0)
```

We have to be a little bit careful about the variable name, since I believe some compilers will warn if a macro-introduced variable shadows an existing local.

I didn't try to use `auto` since I believe we are OK to presume the logger is-a `spdlog::logger`, and that any compiler optimization related to the concrete subclass would still happen even with the upcast to the base.

**Comment by gabime** [comment]
Does it compile when you pass to the macro a shared_ptr<logger> instead of raw?

**Comment by jwnimmer-tri** [comment]
Good point.  I think the solution is to take your proposal and add a const (see below).  It's the pointer that is const, not the pointed-to object that is const, so we can still call the non-const `log` method, and it gets us reference lifetime extension so should work in all cases.

```c++
#define SPDLOG_LOGGER_CALL(logger, level, ...)                            \
  do {                                                                    \
    const auto& SPDLOG_LOGGER_CALL_capture_logger = logger;               \
    if (SPDLOG_LOGGER_CALL_capture_logger->should_log(level) ||           \
        SPDLOG_LOGGER_CALL_capture_logger->should_backtrace()) {          \
      SPDLOG_LOGGER_CALL_capture_logger->log(                             \
          spdlog::source_loc{__FILE__, __LINE__, SPDLOG_FUNCTION}, level, \
          __VA_ARGS__);                                                   \
    }                                                                     \
  } while (0)
```

https://godbolt.org/z/LuEB0b

**Comment by MuwazanaSA** [comment]
@Gabi120  @jwnimmer-tri What's an intermediate resolution to this to get going with this feature? I tried the above suggestions but they do not resolve the issue on 1.4.2.

**Comment by jwnimmer-tri** [comment]
(FYI I'm a user, not a spdlog developer.)

The "evaluate even with logging is off" regression is already fixed on the v1.x branch, but has not yet been tagged for https://github.com/gabime/spdlog/releases as 1.4.3.  So, you could build from the branch if you need the fix ASAP.  Personally I'm just using 1.3.1 until a new tag is cut.

**Comment by MuwazanaSA** [comment]
@jwnimmer-tri  Nope still does not work. I am passing it the shared_ptr of the logger and when I do and set it to INFO, it says base operand doesn't accept -> operator. When I set it to DEBUG mode it compiles but it doesn't log anything.

I have multiple logs. Maybe that's still broken?

**Comment by gabime** [comment]
@jwnimmer-tri and @MuwazanaSA After much consideration, I decided to remove this feature -  It adds 2  additional checks and increases the size and complexity of the generated code.

* Most use cases don't need the redundant checks of the log+traceback levels. 
* It is only applicable when when ```SPDLOG_ACTIVE_LEVEL``` is high enough and one of the args is a costly computation expression
* In cases that it is relevant, It can be easily solved by wrapping with ```if(logger->should_log(debug)) SPDLOG_LOGGER_DEBUG(...)```.

**Comment by jwnimmer-tri** [comment]
Understood, thanks.  I can just add the macro my users want into my downstream project directly, instead of relying on spdlog to provide it natively.

**Comment by vehlwn** [comment]
The issue is still active. spdlog 1.11.0. SPDLOG_* macros evaluate their arguments regardless of the runtime log level.

```cpp
#include <iostream>
#include <spdlog/spdlog.h>
#include <string_view>

int f(const std::string_view s) {
  std::cout << "hello from f(" << s << ")" << std::endl;
  return 42;
}

int main() {
  spdlog::set_level(spdlog::level::critical);
  SPDLOG_TRACE("log record with side effect: {}", f("trace"));
  SPDLOG_DEBUG("log record with side effect: {}", f("debug"));
  SPDLOG_INFO("log record with side effect: {}", f("info"));
  SPDLOG_WARN("log record with side effect: {}", f("warn"));
  SPDLOG_ERROR("log record with side effect: {}", f("error"));
}
```

Compiled with -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE. The output is:

```bash
$ ./mre
hello from f(trace)
hello from f(debug)
hello from f(info)
hello from f(warn)
hello from f(error)
```

>After much consideration, I decided to remove this feature - It adds 2 additional checks and increases the size and complexity of the generated code.

Does this mean this is not a bug even if, for example, Boost.Log does have these runtime checks and it doesn't evaluate arguments for records with lower levels?
