### ISSUE TITLE
Flush before close loses logs in async mode

### ISSUE THREAD

**Issue by oconnore** [gabime/spdlog#147]
Perhaps similar to #145, but in async mode. I haven't figured out a way to force all logs to write + flush to file before closing the program. 

The patch would likely involve changing the busy wait behavior here: https://github.com/gabime/spdlog/blob/cbc8ba72035a3828f3a03e425e7f0d91da6c2ba3/include/spdlog/details/async_log_helper.h#L265-L267 . Using a per-log [condition variable `wait_for`](http://en.cppreference.com/w/cpp/thread/condition_variable/wait_for) instead of a non-interruptible thread `sleep_for` would allow a log-flush to immediately drain the log queue, and then call per-sink flushes. 

Would you be open to a patch? Is there a reason to be busy waiting here at all?

**Comment by gabime** [comment]
This is because the queue is lockfree, so using condition vaiables would defeat this purpose (user thread whould need to acuire the mutex of the condion var).

The cost of this is that when the queue is empty, the backend thread  would spin for 10 times/sec or so.. 

I think it is small price to stay lockless, but I could be wrong of course..

Perhaps overriding the logger::flush in the async logger to drain the queue and only then performing the  flush is a solution for this.

Another option would be chenge the destructor in async_log_helper to process all the messages in the queue before destruction..

**Comment by gabime** [comment]
I think I modify the destructor to process all the messages in the queue before destruction..

**Comment by gabime** [comment]
Fixed in latest commit. Now the logger will first process all messages in the queue before terminating

**Comment by rob-p** [comment]
Awesome; thanks for this!

**Comment by tcwalther** [comment]
I am still encountering this problem in my production app. It occurs when you terminate the program before flushing:

```cpp
#include <iostream>
#include <chrono>
#include <spdlog/spdlog.h>
#include <csignal>


int main() {
  try {
    size_t q_size = 1048576; //queue size must be power of 2
    spdlog::set_async_mode(q_size, spdlog::async_overflow_policy::block_retry,
                           nullptr, std::chrono::seconds(1));
    auto logger = spdlog::daily_logger_mt("main", "log");
    spdlog::set_level(spdlog::level::info);

    logger->info("Test");
    
    // now terminate program
    raise(SIGABRT);
  } catch (const spdlog::spdlog_ex& ex) {
    std::cout << "Log failed: " << ex.what() << std::endl;
  }
  return 0;
}
```

In this small test case, adding `logger->flush()` before the `raise(SIGABRT)` solves the problem. In my production app, I have a `logger->flush()` statement in the destructors of my thread classes (which are properly called), but there, it doesn't solve the problem.

**Comment by gabime** [comment]
afaik  ```raise``` exists the program without calling c++ destrcutors. So this is expected. 
Please try calling ```flush``` from a signal handler.

**Comment by tcwalther** [comment]
Actually, my thread destructors are being called, and they call flush(). In either case, it would be great behaviour if spdlog would call flush automatically.

**Comment by tcwalther** [comment]
I've now implemented a signal handler:

```cpp
  void FlushLogsSignalHandler(int signum)
  {
    auto logger = spdlog::get("main");
    // SignalName(int) simply returns a string, like "SIGINT" for SignalName(SIGINT)
    auto message = tfm::format("Received %s, terminating.", SignalName(signum)); 
    std::cout << message << std::endl;
    logger->info(message);
    logger->flush();
    signal(signum, SIG_DFL);
    kill(getpid(), signum);
  } 
```

I can see the `message` on stdout, but it is not in the log file.

**Comment by gabime** [comment]
ok. i will check it out. which plaform & compiler are you using?

**Comment by tcwalther** [comment]
MacOS, Clang.

```bash
$> c++ --version
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by oconnore** [comment]
@gabime the flush call in @tcwalther 's signal handler is irrelevant because we never made flush drain the queue before it returns. The process is gone long before the async thread completes the queue, and your destructor solution is not called here. I think the only solution to the unclean shutdown is to also implement the other solution you came up with -- making flush drain the queue before it flushes sinks. 

Also, I had originally suggested a cv sleep to allow flush to force-wake the async thread -- I think doing that here might be easier (and perhaps faster for user threads) than making flush spin lock. Since the only blocking it would introduce is where the async thread calls an OS level sleep, perhaps that's acceptable?

**Comment by gabime** [comment]
@oconnore right. calling ```spdlog::drop_all()``` might also do the right right

**Comment by gabime** [comment]
@tcwalther can you see if calling spdlog::drop_all instead of flush() fixes it?

**Comment by oconnore** [comment]
@gabime perhaps making the flush call actually clear queues is a better solution than forcing application developers to intercept all possible unsafe shutdowns in order to trigger `::drop_all`?

**Comment by gabime** [comment]
@oconnore perhaps.. the only issue  is that it might block the caller for long time and that is problematic for a logger that is supposed to be asynchronous..

**Comment by oconnore** [comment]
@gabime isn't blocking reasonable behavior for a flush call? The semantics are usually "do all your writing before I continue". No other logging calls would block. Alternatively, an async flush could trigger a condition variable, or call a callback when it's done writing.

**Comment by gabime** [comment]
@oconnore Yes as long as it is clearly documented, And of course, the user would still have to call flush() in the signal handler.

**Comment by gabime** [comment]
Implemented in 4f52cc4dec993e7ffbfbfd1135b222453f9c90b4

Now calling ```logger->flush()``` will wait until the queue is drained and flushed
