### ISSUE TITLE
Can we use Spdlog's fmt::format?

### ISSUE THREAD

**Issue by nalinigans** [gabime/spdlog#1480]
I could #define SPDLOG_FMT_EXTERNAL and use my own copy of the fmt library. But, 
would like to use Spdlog's bundled fmt::format - on clang/macos - I get unresolved symbols when building in release mode, linking is fine in debug mode. Any ideas?
```
Undefined symbols for architecture x86_64:
 "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > fmt::v6::internal::grouping_impl<char>(fmt::v6::internal::locale_ref)", referenced from:
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<int, fmt::v6::basic_format_specs<char> >::on_num() in test_logger.cc.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<unsigned int, fmt::v6::basic_format_specs<char> >::on_num() in test_logger.cc.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<long long, fmt::v6::basic_format_specs<char> >::on_num() in test_logger.cc.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<unsigned long long, fmt::v6::basic_format_specs<char> >::on_num() in test_logger.cc.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<__int128, fmt::v6::basic_format_specs<char> >::on_num() in test_logger.cc.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<unsigned __int128, fmt::v6::basic_format_specs<char> >::on_num() in test_logger.cc.o
      fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::int_writer<char, fmt::v6::basic_format_specs<char> >::on_num() in test_logger.cc.o
      ...
```

**Comment by gabime** [comment]
How do you build it?

**Comment by nalinigans** [comment]
This is in a cmake project,  nothing out of the ordinary. The project builds a bunch of libraries and tools. We are trying to replace the adhoc logging(mostly std::err messages).
```
#SpdLog
find_package(Spdlog REQUIRED)
include_directories(${SPDLOG_INCLUDE_DIR})
```

**Comment by gabime** [comment]
I mean how did you build spdlog?

**Comment by nalinigans** [comment]
Spdlog is included as a submodule(208eb0ca) and we point to the Spdlog include files using cmake variable SPDLOG_INCLUDE_DIR, using the headers only.

**Comment by nalinigans** [comment]
Solved the issue by reordering the includes - fmt.h preceded by spdlog.h works.
```
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/fmt/fmt.h>
```
Thanks.

**Comment by DarkDimius** [comment]
👋 confirming that this isn't addressed yet and we've run into the same issue.
That said, the workaround ^^^ helped

**Comment by DarkDimius** [comment]
@gabime, could this issue be reopened? thank you

**Comment by gabime** [comment]
Fixed in e3257e56ab32c87640861a5297db07aad2992b60 (I hope).

**Comment by pradyudasu** [comment]
Hello, I still face this issue in gcc 9.3.0 / Ubuntu 20.04 and header-only spdlog (submodule, v1.x branch, current latest).
Similar to others above, in my case, I had to make sure that `spdlog.h` preceded `fmt/ostr.h` in the includes to get rid of all the linker errors.
