### ISSUE TITLE
spdlog causes Apple clang 12.0.5 to crash

### ISSUE THREAD

**Issue by timuraudio** [gabime/spdlog#2045]
spdlog 1.x does not compile on the current version of Apple clang. `file_sinks.cpp` is causing the frontend to crash with a segmentation fault:

```
Building CXX object spdlog/spdlog/CMakeFiles/spdlog.dir/src/file_sinks.cpp.o
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

The only workaround I have found so far is to downgrade from Xcode 12.5.1 to Xcode 12.4 (which comes with an earlier version of clang).

I reported this to LLVM here: https://bugs.llvm.org/show_bug.cgi?id=51456

This appears to be a clang bug, rather than an spdlog bug. But given that spdlog currently does not compile at all on the current toolchain version on macOS, I thought this might be significant enough that you might be able to provide a workaround? Otherwise this is a blocker issue preventing me from using spdlog.

**Comment by gabime** [comment]
Did you try using latest spdlog commit ? There has been a clang 12 related fix recently (https://github.com/gabime/spdlog/pull/2037)

**Comment by gabime** [comment]
Ok. Thanks for reporting. If you find some workaround please update here.

**Comment by Eearslya** [comment]
For what it's worth, this issue seems to have been resolved with the release of Apple Clang 13.0.0. 12.0.5 seemed to have a handful of issues with parsing complex templates, as I experienced several issues with this same segfault even when compiling things other than spdlog.

**Comment by gegles** [comment]
FWIW, I am still getting the seg fault, even with Apple Clang 13.0.0:
```
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-macos11.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
