### ISSUE TITLE
How to set the absolute path of log files correctly（chinese or japanese）

### ISSUE THREAD

**Issue by toby20130333** [gabime/spdlog#2863]
Hi support:
this is a test code:
When the fileName 's path contains chinese or janpanse,the app crash,cannot open the fileName
I need help!
Thank you
`
    QString fileName = QString("%1").arg(nLog);
    {
        auto stdout_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
        stdout_sink->set_level(spdlog::level::off);
 
        auto rotating_sink
            = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(fileName.toStdString().c_str(),
                                                                     maxFileSize,
                                                                     maxFileCount);
        std::vector<spdlog::sink_ptr> sinks{stdout_sink, rotating_sink};
        auto logger = std::make_shared<spdlog::async_logger>("normal_logger",
                                                             sinks.begin(),
                                                             sinks.end(),
                                                             spdlog::thread_pool(),
                                                             spdlog::async_overflow_policy::block);
        logger->set_pattern("%v");

        spdlog::register_logger(logger);
    }
`

**Comment by tt4g** [comment]
Print error messages with `try`-`catch`.
Most questions about not being able to create log files are caused by permission errors.

```cpp
try {

    // your code here.

} catch (const std::exception &ex) {
    std::cerr << ex.what() << std::endl;
}
```

**Comment by tt4g** [comment]
Maybe duplicate #2510

**Comment by toby20130333** [comment]
@tt4g 
But the issue cannot sovled my crash
I fixed with SPDLOG_WCHAR_FILENAMES marco on windows

**Comment by tt4g** [comment]
No source code or error messages are provided, so I have no idea what the cause is.

At least #2510 did not solve the problem with `SPDLOG_WCHAR_FILENAMES` macro, but with `QString::toLocal8Bit().data()`.

**Comment by amanjha491** [comment]
QString fileName = QString("%1").arg(nLog);
{
    auto stdout_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    stdout_sink->set_level(spdlog::level::off);

    // Convert QString to UTF-8 encoded std::string
    auto utf8FileName = fileName.toUtf8().constData();

    auto rotating_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(
        utf8FileName, maxFileSize, maxFileCount);

    std::vector<spdlog::sink_ptr> sinks{stdout_sink, rotating_sink};
    auto logger = std::make_shared<spdlog::async_logger>(
        "normal_logger", sinks.begin(), sinks.end(),
        spdlog::thread_pool(), spdlog::async_overflow_policy::block);
    logger->set_pattern("%v");

    spdlog::register_logger(logger);
}

**Comment by toby20130333** [comment]
@amanjha491  Thank you ,I will try it
